<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 021 21.02.19
 * Time: 10:45
 */

namespace app\models;


use yii\db\ActiveRecord;

class Category extends ActiveRecord
{

    public static function tableName()
    {
        return 'category'; // TODO: Change the autogenerated stub
    }

    protected function getProduct()
    {
        return $this->hasMany(Product::className(), ['category_id' => 'id']); // TODO: Change the autogenerated stub
    }

}
