<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 021 21.02.19
 * Time: 10:45
 */

namespace app\models;


use yii\db\ActiveRecord;

class Product extends ActiveRecord
{

    public static function tableName()
    {
        return 'product'; // TODO: Change the autogenerated stub
    }

    protected static function getProduct()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']); // TODO: Change the autogenerated stub
    }

}