<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 021 21.02.19
 * Time: 10:45
 */

namespace app\models;


use yii\db\ActiveRecord;

class Product extends ActiveRecord
{

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    public static function tableName()
    {
        return 'product'; // TODO: Change the autogenerated stub
    }

    // edits
    protected function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']); // TODO: Change the autogenerated stub
    }

}
